package fr.insa.messenger.tomcat.utils.servlets;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import fr.insa.messenger.tomcat.exceptions.InternalException;

/**
 * @author Damien MOLINA
 */
abstract public class PostServlet extends MyHttpServlet {

    /**
     * Make the current servlet a POST
     * servlet declaring the doPost
     * method.
     *
     * @param request : incoming request.
     * @param response : generated response.
     */
    protected final void doPost(HttpServletRequest request, HttpServletResponse response) throws MyServletException {
        this.handle(request, response) ;
    }

    /**
     * Return a JSON error response.
     *
     * @param request : incoming request.
     * @param response : generated response.
     * @param code : error code.
     * @param message : error message.
     */
    protected void refuse(HttpServletRequest request, HttpServletResponse response, int code, String message) {
        try {
            this.jsonError(response, code, message).send() ;
        } catch (Exception ignored) {}
    }

    /**
     * Handle an incoming exception.
     *
     * @param e : exception instance.
     * @param request : HTTP request.
     * @param response : HTTP response.
     */
    protected void handleException(Exception e, HttpServletRequest request, HttpServletResponse response) {
        // If the exception was generated by our Java code.
        if(e instanceof InternalException) {
            this.refuse(request, response, 400, e.getMessage()) ;
        } else {
            this.refuse(request, response, 500, "Internal server error : " + e.getMessage()) ;
        }
    }

}
